// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "8944f8de-5bbb-4d97-bde7-7c73ef5b0da4";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDeviceModeChange();
void onManuelAngleChange();

String deviceMode;
float current;
float efficiency;
float lux;
float power;
float voltage;
int manuelAngle;
int panelAngle;
bool relayState;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(deviceMode, READWRITE, ON_CHANGE, onDeviceModeChange);
  ArduinoCloud.addProperty(current, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(efficiency, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lux, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(power, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(voltage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(manuelAngle, READWRITE, ON_CHANGE, onManuelAngleChange);
  ArduinoCloud.addProperty(panelAngle, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(relayState, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
